### ISSUE TITLE
How to add a thumbnail ?

### ISSUE THREAD

**Issue by 0xARK** [AirenSoft/OvenPlayer#134]
Hi ! I have a page with a list of streams displayed and I show a preview of the stream when the mouse hovers over a stream. However, when the page is loaded, all the streams display a black screen with the play button.

Is there a way to capture an image of the stream to make a thumbnail of it? And is it possible to remove the play button ? (I already set controls to false).

Regards,

Matéo

**Comment by SangwonOh** [comment]
@0xARK Hi.
1. Is there a way to capture an image of the stream to make a thumbnail of it?
No. But how about play the video and immediately stop the video?

2. Is it possible to remove the play button ?
Play Button is shown at the first time. Because to give the chance to user to playback the video.
But you can hide play button using css on your page like this. 
.op-bigbutton-container {display: none !important;}

**Comment by 0xARK** [comment]
Okay, thanks !
