### ISSUE TITLE
On mobile device not work.

### ISSUE THREAD

**Issue by KIM-IN-KYUM** [AirenSoft/OvenPlayer#146]
Update OME ver. 10.6 to 10.7

On PC working as well.

Mobile device apple and samsung phone just circle looping.

How has same problem? protocol is webrtc.

**Comment by getroot** [comment]
The information you gave is too little to solve the problem.
Depending on what you set up, there may be a variety of problems, including:

-Network connection problem
-Codec compatibility issue
-Problems with WebRTC support on mobile devices
- etc

When reporting a problem, please provide at least OME's Server.xml, ovenmediaengine.log, encoder information, and other information that allows us to recognize the problem, and if possible, share your environment so that we can reproduce the problem (e.g. For WebRTC playback URL)

**Comment by KIM-IN-KYUM** [comment]
Encoder setting change working as well.
If I streaming set interaced couldn't play we. Progressive working as well.

**Comment by SangwonOh** [comment]
It seems that this issue solved. If not please reopen issue. Thanks.
