### ISSUE TITLE
Timeout on connection attempt

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenPlayer#160]
Hi together,

Actually we are trying to build a meeting platform based on OME (really great product). 

But we have this problem:

WE have Webrtc Sources and HLS for fallback but if Webrtc isn't working because of connection problems (firewalls etc) it doesn't get a timeout and so it doesn't switch the source. 

Only the loading indicator is rotating endless.

Is there a possibility to set a timeout for this connection attempt so it would switch to HLS?

**Comment by getroot** [comment]
This is probably a problem to be solved in OvenPlayer. You may be bothered, but could you create an issue on OvenPlayer?

**Comment by morbificagent** [comment]
;-)

**Comment by morbificagent** [comment]
Hi there,
any comments about this?

**Comment by getroot** [comment]
Sorry. This project manager seems to have missed this because he is having too busy days with a commercial project. We'll look at this soon.

**Comment by SangwonOh** [comment]
@morbificagent Hi. Sorry for late response.

Currently, we cannot specify a timeout for the fallback through the player options.

This is because in the playback control part, it must be applied in common to protocols such as WebRTC, HLS, and DASH, and each protocol has different timeout check methods.

However, it will be developed in the future so that you can specify a timeout for Fallback through the player options.

As an alternative, we propose a method of manually controlling the fallback in the application line.

The method is to run a timer when the player is changed to the loading state to check whether the player is playing, and then play the second set Source if not playing.

A code like this.

```javascript
var playbackStarted = false;

// For manual fallback. Make sure to set autoFallback option to false.
var player = OvenPlayer.create("player", {
    autoStart: true,
    autoFallback: false,
    sources: [
        {
            type: 'webrtc',
            file: 'ws://...'
        },
        {
            type: 'hls',
            file: 'http://...'
        }
    ]
});

function checkPlayingAndFallback() {

    var playerState = player.getState();

    if (playerState !== 'playing') {

        // sources[0] is webrtc
        // sources[1] is hls
        // so set to hls fallback by setting current source to 1.
        player.player.setCurrentSource(1);
    }
}

player.on('stateChanged', function (data) {

    if (data.newstate === 'playing') {

        playbackStarted = true;
    }

    // When player state is changed to loading. Start checking playback.
    if (data.newstate === 'loading' && !playbackStarted) {

        var checkInterval = 10 * 1000; // 10 sec

        setTimeout(function () {

            checkPlayingAndFallback();
        }, checkInterval);
    }
});
```

We hope this approach helps you.

**Comment by SangwonOh** [comment]
@morbificagent Hi. It's been a long time since I replied. We added this feature to the latest OvenPlayer. Please check it.

- https://airensoft.gitbook.io/ovenplayer/initialization#webrtcconfig.timeoutmaxretry-and-webrtcconfig.connectiontimeout

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
