### ISSUE TITLE
will it be possible to run ovenplayer in fullscreen automatically?

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenPlayer#200]

**Comment by SangwonOh** [comment]
@Mariano245 Hi. calling `toggleFullScreen` will work. However, it is not recommended to automatically start full screen. This is because, for security reasons, most internet browsers restrict some control from being enforced by the page script. 
In this case, the following error occurs:
`"Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture."`

```javascript
var player = OvenPlayer.create('player', {
    sources: [
        {
            type: 'hls',
            file: 'your_file'
        }
    ]
});

player.on('ready', function () {
   player.toggleFullScreen();
})

**Comment by ScarletBlue** [comment]
@SangwonOh 
Hey man! toggleFullScreen() is not working for me, as it cannot be found. I get the following error:

Uncaught TypeError: Cannot read properties of undefined (reading 'toggleFullScreen')
    at r (ovenplayer.js?e36d:1)
    at Object.t.trigger (ovenplayer.js?e36d:1)
    at eval (ovenplayer.js?e36d:1)

Got any ideas?

**Comment by SangwonOh** [comment]
@ScarletBlue Hi. It seems to be working fine on our demo site(https://demo.ovenplayer.com/). Open the console and try calling the `player.toggleFullScreen()`.

> `Uncaught TypeError: Cannot read properties of undefined (reading 'toggleFullScreen')`

Looking at this log, it looks like there is no player instance defined at that point.

Please let me know under what circumstances the API didn't work.

**Comment by SangwonOh** [comment]
Close this issue due to long inactivity. Please reopen for further discussion.
