### ISSUE TITLE
player.getState(); in real-time without calling it again and again

### ISSUE THREAD

**Issue by yadavendra15** [AirenSoft/OvenPlayer#212]
Hi All,

I've some queries in my mind related to OvenPlayer.

**1.** Is it possible to get the current state of stream (i.e. player.getState(); ) in real-time without calling it again and again.. Or is there something like we get the trigger from the ovenmediaengine that the stream is started or stopped??

**2.** When I start the Screen Share streaming, it takes some time to start the streaming. I didn't find the reason of the delay in the start. 

**3.** While debugging the OvenPlayer, I found that my some packets are losing.
> Last8 LOST PACKET AVG  : 1.5 Current Packet LOST: 0 Total Packet Lost: 12 (8) [0, 0, 8, 4, 0, 0, 0, 0]
> Last8 LOST PACKET AVG  : 1.5 Current Packet LOST: 0 Total Packet Lost: 12 (8) [8, 4, 0, 0, 0, 0, 0, 0]

These type of logs I found in my browser console.

**4.** Is it necessary to use OvenPlayer or we can use another player for ovenmediaengine Streaming??

**Comment by SangwonOh** [comment]
@yadavendra15 Hi.

> 1. Is it possible to get the current state of stream (i.e. player.getState(); ) in real-time without calling it again and again.. Or is there something like we get the trigger from the ovenmediaengine that the stream is started or stopped??

The player does not know the state of the stream. The player has a playing state when the stream is being played, and an error state when playback is not possible due to the reason that the stream does not exist. 
However, the current player state can be delivered through the [stateChanged](https://airensoft.gitbook.io/ovenplayer/api-reference/events#on-statechanged) event even if the getState API is not continuously called.

> 2. When I start the Screen Share streaming, it takes some time to start the streaming. I didn't find the reason of the delay in the start.

Is this an issue about the ovenlivekit?

> 3. While debugging the OvenPlayer, I found that my some packets are losing.

Of course, packet loss may occur depending on network conditions.

> 4. Is it necessary to use OvenPlayer or we can use another player for ovenmediaengine Streaming??

OvenPlayer implements the signaling function to directly play Sub-Second latency stream of OvenMediaEngine. And, if OvenMediaEngine has a new function,  OvenPlayer responds the fastest. If you implement signaling with OME, you can use any other players.

**Comment by yadavendra15** [comment]
Thanks for your reply @SangwonOh 

> Is this an issue about the ovenlivekit?

Yes, I'm using the OvenLiveKit.

**Comment by SangwonOh** [comment]
Yes. We are aware of an issue where the start of streaming screen captures is delayed. We are also working to determine the cause and fix the issue, but this is a low priority. If you leave this issue at https://github.com/AirenSoft/OvenLiveKit-Web/issues, we will let you know as we have some progress. By the way, For this reason, the screen capture function has not been officially opened, but you are amazing to find and use it. Thnaks.

**Comment by SangwonOh** [comment]
And in case of packet loss, playing the stream as UDP can cause packet loss. Playing the stream with TCP there will be no packet loss. To play stream over TCP, see here (https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#webrtc-over-tcp-with-ovenplayer).

**Comment by yadavendra15** [comment]
Thanks again :100: :+1:  , Closing the issue...
