### ISSUE TITLE
Playing HLS protocol with ovenplayer has for me a delay of approximately 20 seconds, is it possible to reduce it to less than 10 seconds?

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenPlayer#247]

**Comment by nxtreaming** [comment]
You can modify the Server.xml, such as:
`  
<HLS>
          <SegmentDuration>2</SegmentDuration>
          <SegmentCount>3</SegmentCount>
          <CrossDomains>
                  <Url>*</Url>
          </CrossDomains>
</HLS>`

The SegmentDuration is 5s by default,  so you have about 20s delay

**Comment by basisbit** [comment]
I'd suggest only using such "short" `SegmentDuration" if you either use a http1.1+ supporting reverse proxy like Nginx in front of OvenMediaEngine, or if all your customers are within the same country / geographic region of your server location.

Otherwise, only 5 or 6 seconds as segment size will suffice for tcp slow start to catch up for each segment and then still have enough time to download the rest of the file.

**Comment by Mariano245** [comment]
Thank you very much for answering, I think that the default value of the duration of the segment should be optimal, but I will try to lower it to 3 and evaluate the results. Greetings

**Comment by SangwonOh** [comment]
Also you can try hls Manage Latency options you can find  in our demo page (demo.ovenplayer.com)

And we are closing the issue due to a long period of inactivity.
If further discussion is needed, please open a new issue.
