### ISSUE TITLE
I wonder which function indicates that OvenPlayer finishes receiving a frame.

### ISSUE THREAD

**Issue by htliu6** [AirenSoft/OvenPlayer#263]
Is there anybody familiar with above functions? @dimiden @genofire @hernanrz @getroot Thanks!

**Comment by genofire** [comment]
You mean receiving a single Video frame (one image)?

I would wonder if there is any event handler / function for that, it will be fire so many times and maybe slow down the Browser. (I am not willing to search in the code for such, because it is no good idea to use this function - why you are searching for it?)

But i am not a developer of this project, so do not ask me. (Why you highlight me? Do you find me because I document or fix something here?)

**Comment by htliu6** [comment]
Thanks for your kindly reply! I would like to acquire the total number of received frames in a real-time manner. Is there any function or variable indicating this? Thanks!

**Comment by genofire** [comment]
Ahh you like to see the framerate per seconds of your current stream. - okay that should be possible (and maybe implemented).

**Comment by SangwonOh** [comment]
> I would like to acquire the total number of received frames in a real-time manner

@htliu6 Hi. You can see the frame information by using html video api.

```javascript
ovenPlayerInstance.getMediaElement().getVideoPlaybackQuality();
```
returns
```javascript
{
  corruptedVideoFrames: 0
  creationTime: 103839.20000000019
  droppedVideoFrames: 539
  totalVideoFrames: 2990
}
```


Ref.
OvenPlayer Get Video element

> https://airensoft.gitbook.io/ovenplayer/api-reference/api#getmediaelement

HTML VIDEO API: getVideoPlaybackQuality

> https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/getVideoPlaybackQuality

**Comment by genofire** [comment]
So you could close this issue @htliu6 ?

**Comment by htliu6** [comment]
Sure! Thanks a lot!
