### ISSUE TITLE
option to disable the http dns resolver? 

### ISSUE THREAD

**Issue by michaeleino** [AirenSoft/OvenPlayer#264]
we have the streaming domain hosted locally on the LAN, and we have a local DNS to resolve such local domains...

with firefox, we can't set the domain like this, as the .js is trying to resolve from the google
![Screenshot from 2022-04-09 14-50-33](https://user-images.githubusercontent.com/6287237/162574912-32057808-281c-4da6-92be-0cde22a68e42.png)
Is there a way to disable this by config? or
Set my local custom dns instead? or any other good workarounds ?

I have tried to mess with the function on compiled file like below, and it works!
![Screenshot from 2022-04-09 14-55-10](https://user-images.githubusercontent.com/6287237/162574996-a7f6dc57-887e-4a29-a152-08ce298453ec.png)

**Comment by SangwonOh** [comment]
@michaeleino Hi.

There was a problem with the Firefox browser, so I was doing DNS resolution.

> firefox browser throws a candidate parsing exception when a domain name is set at the address property. So we resolve the dns using google dns resolve api.

First of all, I want to check if it has been fixed in the latest Firefox browser and try to delete that logic.
If the problem remains in the latest Firefox, we will add or try to exclude the logic.
(Furthermore, it is not appropriate to use a specific vendor's capabilities to solve this problem. So, whenever possible, I try to delete that feature.)

We'll let you know when we patch it.

Thanks :)

**Comment by SangwonOh** [comment]
@michaeleino Hi. please check out our latest release! Thanks.

> https://github.com/AirenSoft/OvenPlayer/releases/tag/v0.10.18

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
