### ISSUE TITLE
OME WebRTC exclusive only to OvenPlayer?

### ISSUE THREAD

**Issue by sebdott** [AirenSoft/OvenPlayer#298]
For OME WebRTC contains specific requirement (Signalling Protocol Conforms to the OME Specification)
Not too sure if its possible to run it in another video player.

Do you know any other alternative player to play the WebRtc link in React Native ?

Example:
wss://xxxx/app/stream

**Comment by SangwonOh** [comment]
@sebdott  No other player seems to have implemented our signaling. But because standard html specifications are used, if signaling is implemented well, I think it will work well for other players as well. You can even make it play using only the html video element. 

https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#signalling

**Comment by Yuvraj-Mori** [comment]
any idea about React-Native Side getting Error on Oven Media Webrtc Connection peerConnection.setLocalDescription(desc)

**Comment by Yuvraj-Mori** [comment]
React-Native Producing Error on Ovenmedia Engine candidate add in  peerConnection.addIceCandidate(candidate)
here candidate : {"candidate": "candidate:0 1 UDP 50 135.*.*.24 10000 typ host", "sdpMLineIndex": 0}

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please open a new issue.
