### ISSUE TITLE
Capability to rewind back on a live stream

### ISSUE THREAD

**Issue by TalkingIsland** [AirenSoft/OvenPlayer#307]
Is this possible? And if not, then is this in the near-term plans?

The idea is to make it so that OME doesn't just stream, but so that also during the livestream it would allow the viewer to rewind back (such as if the viewer tuned in late, or wanted to watch a particular portion again). 

Thanks

**Comment by getroot** [comment]
With WebRTC, this is almost impossible. To make this possible, OvenPlayer may need to use LLHLS to go back in time.

In LLHLS, this must first be implemented on the server. OvenMediaEngine has plans to implement this. It will probably be implemented early next year.

**Comment by TalkingIsland** [comment]
I see, thank you for the update. Looking forward to this new feature.

**Comment by SangwonOh** [comment]
@TalkingIsland  Hi.
Live rewind back feature added to OvenMediaEngine. Please refer this manual https://airensoft.gitbook.io/ovenmediaengine/streaming/low-latency-hls#drm-beta

And also you can test it at https://demo.ovenplayer.com

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
