### ISSUE TITLE
Not able to run the player in mobile browser but work fine in desktop 

### ISSUE THREAD

**Issue by chandan688** [AirenSoft/OvenPlayer#309]
Hi Team, we are getting an issue with player, when we implement the ads code then mobile browser player shows this error "media not ble to download"

Here is the url 

https://publictv.in/PTV3.html

Only ads is working.
Please fix this issue asap

**Comment by chandan688** [comment]
any update on this?

**Comment by SangwonOh** [comment]
@chandan688 Hi. In our testbed, there seems to be no problem. Let us know what test environment is causing the problem.
(For example, OS, OS version, Browser, Browser version etc...)

**Comment by chandan688** [comment]
It's issue with chrome browser in mobile as well as in mobile mode under inspect element.

The issue is ads running but live streaming is not working with the ads tag. When we remove the adtag url then streaming / Player is working fine in both browser mode.

Here is the url https://publictv.in/PTV3.html

![Screenshot_20221013_185211](https://user-images.githubusercontent.com/11809218/195608300-2f85e748-99dc-4073-9ddb-db0db2585e5a.jpg)
![Screenshot_20221013_185204](https://user-images.githubusercontent.com/11809218/195608305-8478bf0d-5e6f-43b9-a6d8-d2335e8324cf.jpg)

**Comment by chandan688** [comment]
any update on this issue?

**Comment by chandan688** [comment]
Any update on this. Am waiting for the solution.

**Comment by getroot** [comment]
@chandan688 

I'm not a player developer, but since you keep pushing the OvenPlayer developer, so I took a look at this. (Don't push developers in the open source community. They can be very busy with other things and lose motivation to run open source.)

The site you provide has a mixed content problem first.
Could not load http streaming url from https page. You have to replace http://livestream.knowtable.xyz:5443/show/streams/Publictv_adaptive.m3u8 with https://livestream.knowtable.xyz:5443/show/streams/Publictv_adaptive.m3u8 .

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
